### ISSUE TITLE
Opt out of "Merge for-declaration with the previous declaration"

### ISSUE THREAD

**Issue by thscott** [laurentlb/shader-minifier#397]
Would it be possible to have a way to opt out of the change introduced in #371?

The form `int a=2, b=3; for (; ...)` is not valid in GLSL ES, and hence not valid in WebGL 1.

See Appendix A of the spec [here](https://www.khronos.org/files/opengles_shading_language.pdf), specifically these lines:

> - The for statement has the form:
>     - for ( _init-declaration_ ; _condition_ ; _expression_ ) _statement_
> - init-declaration has the form:
>     - _type-specifier_ identifier = constant-expression
>
> Consequently the loop variable cannot be a global variable.

**Comment by laurentlb** [comment]
Nice finding. I should just rollback this commit. The optim is not worth it.

**Comment by therontarigo** [comment]
I'd rather not lose this optimization because of such an ancient GLES version.
Checking the compression stats, the only shaders for which it hurt compression were those also using `--no-renaming` - which breaks the context models anyway, so they shouldn't be trusted too much.

It should be easy to add `--language` option with `hlsl`, `glsl`, `glsl100es` `glsl300es` as choices, so that we don't need an optimization-specific flag here, even if this is the only thing it will affect thus far.  Webgl1 (100 es) is the only lang with this restriction.  Desktop GLSL also allows int literals in more places than 300es does, though this isn't exploited yet.

**Comment by laurentlb** [comment]
In https://github.com/laurentlb/shader-minifier/commit/5b8f9453863dab087460a1af73de1eca277e9e0f#diff-5a7085bc7afa14a48d0b7c3c68992949b5c04e13ef2f76a46eb17d106b6c6d62, the compression tests are all done with the default flags and include renaming (so they don't match the .expected files). Based on that, this optimization doesn't save space after compression.

A reason to keep it is that it can be useful for people who care about the uncompressed size. It may also help future optimizations (maybe).

**Comment by therontarigo** [comment]
Thanks, clearly I was thinking compression inputs differed only by `--format text`.  I don't mind seeing it disabled for now.  This puts #398 as low priority, though it relates also to another optimization I'm currently working.
